library(data.table)
library(lpSolve)
library(janitor)
library(lpSolveAPI)
feed <- read.csv("feed_base.csv")
f <- read.csv("Feed_const.csv")
feed_const <- data.table(f$Feed, f$min*(feed$X.MS/100), f$max*(feed$X.MS/100))
colnames(feed_const)<-c("feed", "min", "max")
nutrient_const <- read.csv(("Nutrient_const.csv"))
feed <- data.table(feed)
feed$DM_cost <- feed$X..ton/(feed$X.MS/100)
